# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-06 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20170806_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
